version: '3'
services:
  react-fetchify:
    build:
      context: .
    container_name: react_app
    command: "npm start"
    expose:
      - "8080"
    ports:
      - "8080:8080"
    volumes:
      - ./fetchify:/src
      - ./fetchify/node_modules
    