//SavedData actions
export const SAVE_DATA = "SAVE_DATA";
export const SEND_DATA_URL = "SET_DATA_URL";
export const SET_SEND_BODY = "SET_SEND_BODY";
export const SEND_SAVED_DATA = "SEND_SAVED_DATA";
export const ADD_SEND_HEADER = "ADD_SEND_HEADER";
export const CLEAR_SAVED_DATA = "CLEAR_SAVED_DATA";
export const SEND_DATA_FAILED = "SEND_DATA_FAILED";
export const SEND_DATA_SUCCESS = "SEND_DATA_SUCCESS";
export const REMOVE_SAVED_DATA = "REMOVE_SAVED_DATA";
export const REMOVE_SEND_HEADER = "REMOVE_SEND_HEADER";
export const CHANGE_SEND_METHOD = "CHANGE_SEND_METHOD";
export const TOGGLE_SEND_HEADER = "TOGGLE_SEND_HEADER";
export const TOGGLE_SHOW_HEADERS = "TOGGLE_SHOW_HEADERS";
export const SEND_URL_VALIDATION = "SEND_URL_VALIDATION";
export const SET_SEND_HEADER_KEY = "SET_SEND_HEADER_KEY";
export const SET_SEND_HEADER_VALUE = "SET_SEND_HEADER_VALUE";
export const REMOVE_LAST_SEND_HEADER = "REMOVE_LAST_SEND_HEADER";
export const TOGGLE_SHOW_CUSTOM_JSON = "TOGGLE_SHOW_CUSTOM_JSON";

//MainPage actions
export const FETCH_DATA = "FETCH_DATA";
export const SET_GET_URL = "SET_GET_URL";
export const SET_GET_BODY = "SET_GET_BODY";
export const REMOVE_ERROR = "REMOVE_ERROR";
export const SET_GET_METHOD = "SET_GET_METHOD";
export const SET_GET_PARAMS = "SET_GET_PARAMS";
export const SET_GET_HEADERS = "SET_GET_HEADERS";
export const FETCH_DATA_ERROR = "FETCH_DATA_ERROR";
export const SAVE_BUTTON_CLICK = "SAVE_BUTTON_CLICK";
export const REQUEST_SEND_START = "REQUEST_SEND_START";
export const GET_URL_AND_STATUS = "GET_URL_AND_STATUS";
export const URL_VALIDATION_ERROR = "URL_VALIDATION_ERROR";
export const BODY_VALIDATION_ERROR = "BODY_VALIDATION_ERROR";
export const TOGGLE_GET_PARAMS_BUTTON = "TOGGLE_SHOW_PARAMS_BUTTON";
export const TOGGLE_GET_HEADERS_BUTTON = "TOGGLE_GET_HEADERS_BUTTON";
//Params
export const GET_PARAM_KEY = "GET_PARAM_KEY";
export const GET_PARAM_VALUE = "GET_PARAM_VALUE";
export const ADD_GET_PARAM_ROW = "ADD_GET_PARAM_ROW";
export const REMOVE_LAST_PARAM = "REMOVE_LAST_PARAM";
export const TOOGLE_PARAM_STATUS = "TOOGLE_PARAM_STATUS";
export const REMOVE_SELECTED_PARAM = "REMOVE_SELECTED_PARAM";
//Headers
export const GET_HEADER_KEY = "GET_HEADER_KEY";
export const GET_HEADER_VALUE = "GET_HEADER_VALUE";
export const ADD_GET_HEADER_ROW = "ADD_GET_HEADER_ROW";
export const REMOVE_LAST_HEADER = "REMOVE_LAST_HEADER";
export const TOOGLE_HEADER_STATUS = "TOOGLE_HEADER_STATUS";
export const REMOVE_SELECTED_HEADER = "REMOVE_SELECTED_HEADER";

//Builder Actions
export const CLEAR_JSON = "CLEAR_JSON";
export const ADD_KEY_ROW = "ADD_KEY_ROW";
export const SET_PREVIEW = "SET_PREVIEW";
export const GET_JSON_KEY = "GET_JSON_KEY";
export const GET_JSON_VALUE = "GET_JSON_VALUE";
export const REMOVE_LAST_KEY = "REMOVE_LAST_KEY";
export const SET_DRAG_STATUS = "SET_DRAG_STATUS";
export const CLEAR_KEY_VALUE = "CLEAR_KEY_VALUE";
export const CLEAR_BODY_TABLE = "CLEAR_BODY_TABLE";
export const TOOGLE_KEY_STATUS = "TOOGLE_KEY_STATUS";
export const REMOVE_SELECTED_KEY = "REMOVE_SELECTED_KEY";
